// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoOZxknzwgKJiVxCcIm02LL78DqFwseWs',
    appId: '1:520285505256:web:2fc7df9ab0353d7573ab5d',
    messagingSenderId: '520285505256',
    projectId: 'admin-auth-22fe6',
    authDomain: 'admin-auth-22fe6.firebaseapp.com',
    storageBucket: 'admin-auth-22fe6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbW-mvt0BHmlSkc1Pw8kz0NuiZMudpHc8',
    appId: '1:520285505256:android:a5d96e9b43d6ffd273ab5d',
    messagingSenderId: '520285505256',
    projectId: 'admin-auth-22fe6',
    storageBucket: 'admin-auth-22fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDviiGksewzWTn5k0dZu64UJUaMt15k_Mo',
    appId: '1:520285505256:ios:8f54624f7dda273673ab5d',
    messagingSenderId: '520285505256',
    projectId: 'admin-auth-22fe6',
    storageBucket: 'admin-auth-22fe6.appspot.com',
    iosClientId: '520285505256-gonl2pf846bces26kj69ggvu91f8gj7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDviiGksewzWTn5k0dZu64UJUaMt15k_Mo',
    appId: '1:520285505256:ios:5a8c3496bb7da9fd73ab5d',
    messagingSenderId: '520285505256',
    projectId: 'admin-auth-22fe6',
    storageBucket: 'admin-auth-22fe6.appspot.com',
    iosClientId: '520285505256-jei6o46p8iag4bpd4ov1922o0puj9oc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
